# /etc/nginx/sites-available/riddle
limit_req_zone $binary_remote_addr zone=general:1m rate=10r/s;
limit_req_zone $binary_remote_addr zone=api:1m rate=5r/s;

server {

	server_name example.com;

	location /api/v1/ {
		proxy_pass http://unix:/run/riddle/riddle.sock:/;
		proxy_set_header Host $http_host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;

		limit_req zone=api burst=10 nodelay;
		limit_req_status 429;
	}
	location / {
		root /var/www/riddle;
		index index.html;
		limit_rate 500k;
		limit_req zone=general burst=10 nodelay;
		limit_req_status 429;
	}

	#listen [::]:443 ssl http2 ipv6only=on; # managed by Certbot
	listen 443 ssl http2; # managed by Certbot
	ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem; # managed by Certbot
	ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem; # managed by Certbot
	include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
	ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

server {
	if ($host = example.com) {
		return 301 https://$host$request_uri;
	} # managed by Certbot


	listen 80 default_server;
	#listen [::]:80 default_server;

	server_name example.com;
   	return 404; # managed by Certbot
}

